version: '3'
services:
    flyway:
        image: flyway/flyway:7.7.1
        environment:
             - FLYWAY_USER=docker
             - FLYWAY_PASSWORD=docker
        command: migrate 
                  -url=jdbc:postgresql://postgres:5432/nonzero 
                  -locations=filesystem:/flyway/sql 
                  -connectRetries=60
                  -mixed=true
        volumes:
          - ./sql:/flyway/sql
        depends_on:
          postgres:
            condition:
                service_healthy

    postgres:
        image: postgres:11
        restart: always
        ports:
        - 5432:5432
        environment:
        - POSTGRES_USER=docker
        - POSTGRES_PASSWORD=docker
        volumes:
        - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U docker"]
            interval: 5s
            timeout: 5s
            retries: 5
    
    pgadmin:
        image: dpage/pgadmin4
        restart: always
        ports:
        - 5431:80
        depends_on:
            - postgres
        environment:
            PGADMIN_DEFAULT_EMAIL: $${PGADMIN_DEFAULT_EMAIL:-user@domain.org}
            PGADMIN_DEFAULT_PASSWORD: $${PGADMIN_DEFAULT_PASSWORD:-docker}
            PGADMIN_CONFIG_SERVER_MODE: 'False'
            PGADMIN_SERVER_JSON_FILE: '/pgadmin4/servers.json'
        volumes:
        - ./sql/pgadmin_servers.json:/pgadmin4/servers.json 
        